### PR TITLE
Temp rit tides port master upgrade gw surrogate api

### PR DESCRIPTION
**Pull request by jlange2010**
I have checked this runs with the latest version of gwsurrogate (0.9.8) and runs with NRSur7dq4 and NRHybSur3dq8. Infastructure exist to use NRHybSur3dq8T, but not verified. Waiting to hear back from Scott et. al. as to what to do with the fmin=0 issue.

### CODE REVIEW

**Comment by oshaughn** [comment]
Why are there any changes in ILE_batchmode?  You are reverting changes to a routine you should not be changing

**Comment by jlange2010** [comment]
These try/except statements ruin runs because the dag sees the job as succeeding instead of failing. Plus it is hard to tell what the error actually is.

**Comment by oshaughn** [comment]
We put in the try/except because of many problems on runs ... failures for bad reasons eg a single malconfigured OSG node or a single job failure from a length problem would bring a run crashing down.  Without try/except the runs were too fragile in my experience

**Comment by jlange2010** [comment]
I'd rather have things crash and just relaunch the dag than have things not crash, "finish" and then realize the whole run I thought was actually running correct was not. Every time I update my branch I end up commenting this out. We need to at least have a flag to turn this on and off; I find it quite annoying when running with it.

**Comment by oshaughn** [comment]
When we are doing PP plots and large-scale runs, we can't be restarting jobs piecemeal.  Can you please document (preferably with LIGO chat first) a concrete problem that arises from the try/except.
   Also, more generally, we should split MR which change different pieces of code.
   This is delaying the merge ... just break it up and submit it

**Comment by oshaughn** [comment]
Also, you have changed the converter for aligned spin to be precessing? This will break old aligned-spin code.  Please define a new converter as needed, and update the appropriate  coordinate conversion routine  (see my_converter in the text)

**Comment by jlange2010** [comment]
I changed the converter the converter to work with the new API format. If you look it's still aligned. I tested to see if anything broke. Everything worked fine...

**Comment by oshaughn** [comment]
Ok, if it's a wholesale API change for all models that's fine.
Please do revert the changes to the other file though so we can close this out.

**Pull request closed without merging**
